### ISSUE TITLE
Suggestions: Signup page

### ISSUE THREAD

**Issue by NoMoneyDev** [OmegaOoh/ku-polls#52]
This [document](https://cpske.github.io/ISP/django/authentication) provides how to create a simple signup page.
The instructions are under Extra Material sections.

**Comment by OmegaOoh** [comment]
I've added the sign up page in #53 which will be merged into master branch soon. 
![Signup page](https://github.com/user-attachments/assets/ce2053c4-7579-41b7-bd80-d7921ec6f1cf)
